import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './(home)/_components/Navbar'
import Footer from './(home)/_components/Footer'
import Provider from '@/components/providers/Provider'
import  ToastProvider  from '@/components/providers/react-toast-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark `}><Provider><ToastProvider/><Navbar/><div className="pt-16">{children}</div> <Footer/></Provider></body>
    </html>
  )
}
